[[main]]
  name = "Install"
  url = "/install"
  weight = 10

[[main]]
  name = "Guides"
  url = "/guides"
  weight = 30

[[main]]
  name = "Reference"
  url = "/reference"
  weight = 40

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 50

[[main]]
  name = "GitHub"
  url = "https://github.com/benbjohnson/litestream"
  weight = 60

[[main]]
  name = "Slack"
  url = "https://join.slack.com/t/litestream/shared_invite/zt-n0j4s3ci-lx1JziR3bV6L2NMF723H3Q"
  weight = 70


[[docs]]
  name = "Install"
  weight = 10
  identifier = "install"
  url = "/install"

[[docs]]
  name = "Getting Started"
  weight = 20
  identifier = "getting-started"
  url = "/getting-started/"

[[docs]]
  name = "Tips & Caveats"
  weight = 25
  identifier = "tips"
  url = "/tips/"

[[docs]]
  name = "Guides"
  weight = 30
  identifier = "guides"
  url = "/guides/"

[[docs]]
  name = "How it Works"
  weight = 40
  identifier = "how-it-works"
  url = "/how-it-works/"

[[docs]]
  name = "Reference"
  weight = 50
  identifier = "reference"
  url = "/reference/"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/litestreamio"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/benbjohnson/litestream"
  weight = 20
