apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: myapp
    release: prometheus
  name: myapp
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: myapp
